
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meetingroom?useSSL=false&serverTimezone=Asia/Tokyo
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080
